name: Go CI

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install dependencies
        run: |
          cd Go
          go mod download

      - name: Verify dependencies
        run: |
          cd Go
          go mod verify

      - name: Run tests
        run: go test ./Go/...

      - name: Lint code
        run: golangci-lint run ./Go
